package com.phenikaa.thesis.thesis.entity.enums;

public enum ThesisStatus {
    NOT_ELIGIBLE,
    ELIGIBLE_FOR_THESIS,
    TOPIC_PENDING_APPROVAL,
    TOPIC_APPROVED,
    TOPIC_REJECTED,
    TOPIC_ASSIGNED,
    OUTLINE_SUBMITTED,
    OUTLINE_APPROVED,
    OUTLINE_REJECTED,
    IN_PROGRESS,
    DEFENSE_REQUESTED,
    DEFENSE_APPROVED,
    DEFENSE_REJECTED,
    READY_FOR_DEFENSE,
    DEFENDING,
    GRADED,
    PASSED,
    FAILED,
    COMPLETED
}
